version: "3.2"
services:
  backend:
    container_name: top-api
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/course
    env_file:
      - ./.env
    depends_on:
      - mongo
  mongo: 
    container_name: mongo
    restart: always
    image: mongo:6.0.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/app/database
volumes:
  mongo-data: